services:
  auth-service:
    container_name: auth-service
    image: ghcr.io/digitrack-inc/auth-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:9101
    volumes:
      - ./repository/:/app/repository/
    env_file:
      - environments/.env.local
    external_links:
      - postgres_main:postgres
    networks:
      - app_network 